import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = [];
page.on('pageerror', e => errs.push('[pageerror] ' + e.message));
page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
await page.addInitScript(() => { localStorage.setItem('mf_settings', JSON.stringify({ quality: 'low' })); HTMLCanvasElement.prototype.requestPointerLock = function () { return Promise.resolve(); }; });
await page.goto('http://localhost:8080/index.html');
await page.waitForFunction(() => window.game && window.game.state === 'menu', null, { timeout: 120000 });
await page.evaluate(() => game.menu.showLoadouts('main')); await page.waitForTimeout(800); await page.screenshot({ path: 'test/loadout.png' });
await page.click('[data-g=primary]'); await page.waitForTimeout(400);
await page.click('.gs-slot[data-s=optic]'); await page.waitForTimeout(300);
await page.hover('.gs-att[data-id=acog]'); await page.waitForTimeout(1200); await page.screenshot({ path: 'test/gunsmith.png' });
await page.click('.gs-att[data-id=acog]'); await page.click('.gs-slot[data-s=camo]'); await page.click('.camo[data-c=gold]'); await page.waitForTimeout(1200); await page.screenshot({ path: 'test/gunsmith2.png' });
await page.click('[data-a=done]'); await page.click('[data-p=perks]'); await page.waitForTimeout(300); await page.screenshot({ path: 'test/perks.png' });
await page.click('.pick[data-id=overkill]'); await page.click('[data-a=ok]');
await page.click('[data-w=secondary]'); await page.waitForTimeout(300); await page.screenshot({ path: 'test/wpick.png' });
await page.click('.pick[data-id=ak]'); await page.waitForTimeout(300);
const cls = await page.evaluate(() => game.profile.classes[0]);
console.log(JSON.stringify(cls));
await page.evaluate(() => game.menu.showSettings('main')); await page.waitForTimeout(300); await page.screenshot({ path: 'test/settings.png' });
await page.evaluate(() => game.startGame('mp', { mode: 'dom', map: 'yard', diff: 1, allies: 3, enemies: 4, scoreLimit: 200, timeLimit: 5 }));
await page.waitForTimeout(1500);
await page.evaluate(() => game.pause(true)); await page.waitForTimeout(500); await page.screenshot({ path: 'test/pause.png' });
await page.click('[data-a=class]'); await page.waitForTimeout(300); await page.screenshot({ path: 'test/classsel.png' });
await page.click('.pick[data-i="2"]'); await page.waitForTimeout(300);
console.log('after class', await page.evaluate(() => [game.menu.screen, game.paused, !!game.mode.nextLoadout]));
await page.click('[data-a=resume]'); await page.waitForTimeout(300);
console.log('resumed', await page.evaluate(() => [game.menu.screen, game.paused]));
await page.evaluate(() => { game.hud.showScoreboard(true); }); await page.waitForTimeout(400); await page.screenshot({ path: 'test/score.png' });
console.log(errs.join('\n'));
await browser.close();
